# Same with this
#  fill it up with real things you want to filter out

title:
  - bureaucrat
  - chief
  - blernsball
  - ultimate
  - robot
  - fighting

company:
  - cryogenics

description:
  - zoidberg

global:
  - omicron
  - persei